import {firstValueFrom} from 'rxjs';
import type {SearchUserResponse} from 'src/repositories/jira-repository';
import {jiraRepository} from 'src/repositories/jira-repository';

export const handleTestUser = async () => {
  const users = [
    'Anhlq',
    'Anhndq7',
    'AnhNH94',
    'BaoTV10',
    'binhpn9',
    'ChauNTM32',
    'CuongNK19',
    'DatNHP',
    'DefaultAccount',
    'DoanPV9',
    'DucTA16',
    'DungLA15',
    'DungLT109',
    'DungNV143',
    'duydv28',
    'DuyNK38',
    'GamHTH2',
    'Guest',
    'HaLH15',
    'HanhNm17',
    'hatt87',
    'HienNT245',
    'hiepnh',
    'hieunm94',
    'hieunt',
    'hoandm2',
    'hoant255',
    'hungnv222',
    'hungvm',
    'huongnt242',
    'HuyBQ23',
    'HuyenDT65',
    'huyenhn5',
    'huyenntt195',
    'k3s',
    'KhangDM2',
    'khanhhv',
    'KhanhVN8',
    'kienpn5',
    'LinhDTT30',
    'LinhHT40',
    'LinhND37',
    'linhnpn2',
    'LinhNV90',
    'maidth4',
    'MaiVTT14',
    'MaoNG2',
    'minhtq44',
    'ngochv4',
    'nhungvh6',
    'ninhth6',
    'PhapNX',
    'PhuongBTB5',
    'PhuongVCH',
    'QuanNT32',
    'QuyenTT26',
    'rd-anhnv',
    'rd-cungdd',
    'rd-dattt',
    'rd-hoangnv',
    'rd-kiendq',
    'rd-kiendv',
    'rd-nhungdh',
    'rd-quynhlt',
    'rd-tuannd',
    'rd-tuvh',
    'sonbt',
    'TaiNN3',
    'TaiVM2',
    'thaont121',
    'thaont209',
    'thomnh',
    'ThuNT27',
    'ThuyPT92',
    'TienTV20',
    'TrangNT175',
    'trungbx',
    'tuanhn9',
    'tunglh9',
    'tungtn12',
    'UyenNTH6',
    'vudt19',
    'WDAGUtilityAccount',
    'xuyennt14',
  ];
  for (const user of users) {
    const res: SearchUserResponse = await firstValueFrom(
      jiraRepository.searchUser(user),
    );
    if (res.total >= 1) {
      const u = res.users[0];
      console.log(`${u.name},${u.displayName}`);
    } else {
      console.log(`${user},`);
    }
  }
};
