name: Build and Publish Release
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project
        run: |
          yarn install
          yarn build
          zip -r extension.zip dist

      - name: Publish release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          body: This is an automated release created by GitHub Actions.
          draft: false
          prerelease: false

      - name: Upload asset
        uses: actions/upload-release-asset@v1
        with:
          asset_path: extension.zip
          asset_name: extension.zip
          asset_content_type: application/zip
          release_id: ${{ github.event.release.id }}
